services:
  jenkins:
    build: .
    container_name: jenkins-ngrok
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - jenkins_home:/var/jenkins_home
    image: jenkins:ngrok

volumes:
  jenkins_home: